# Build settings
permalink: none
markdown: kramdown
highlighter: pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: end2end
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://nandomoreira.me
baseurl: "/end2end"

google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/end2end
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Bayu Prastianto
  job: looking for a real job
  bio: "Getting things done."
  thumb: /images/author.jpg
  email: bayu.prastianto@outlook.com
  url: https://bayuprastianto.github.io/
  # github: https://github.com/nandomoreirame
  twitter: https://twitter.com/bayupee
  facebook: https://facebook.com/bayupee1
  # linkedin: https://linkedin.com/in/nandomoreirame

# navbar pages
navbar:
  - slug: tentang
    title: Tentang
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
